import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthLinks from "@/app/components/AuthLinks";
import { SessionProvider } from "next-auth/react";
import Profile from "@/app/components/profile";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
        <div className="flex items-center justify-end py-5 px-10 pl-10 gap-4">
            <div className="flex gap-4">
            <AuthLinks />
            <Profile />
            </div>
          </div>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
